package visao;

import dao.veiculo.VeiculoDAOMySQL;
import modelo.Veiculo;
import dao.veiculo.VeiculoDAO;

public class FrmCadastroVeiculo extends javax.swing.JFrame {

    public FrmCadastroVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFPlaca = new javax.swing.JTextField();
        jTFModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFLugares = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JBTSair = new javax.swing.JButton();
        JBTLimpar = new javax.swing.JButton();
        jBTSalvar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        JBTAlterar = new javax.swing.JButton();
        JBTListar = new javax.swing.JButton();
        jTFValorAluguel = new javax.swing.JTextField();
        JBTReajustar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Dados de Veículo");

        jLabel2.setText("Placa:");

        jTFPlaca.setName("JTFNome"); // NOI18N

        jTFModelo.setName("JTFNome"); // NOI18N

        jLabel3.setText("Modelo:");

        jLabel4.setText("Marca:");

        jTFMarca.setName("JTFNome"); // NOI18N

        jLabel5.setText("Lugares:");

        jTFLugares.setName("JTFNome"); // NOI18N

        jLabel6.setText("Valor Aluguel");

        JBTSair.setText("Sair");
        JBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTSairActionPerformed(evt);
            }
        });

        JBTLimpar.setText("Limpar");
        JBTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTLimparActionPerformed(evt);
            }
        });

        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        JBTAlterar.setText("Alterar");
        JBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTAlterarActionPerformed(evt);
            }
        });

        JBTListar.setText("Listar");
        JBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTListarActionPerformed(evt);
            }
        });

        jTFValorAluguel.setName("JTFNome"); // NOI18N

        JBTReajustar.setText("Reajustar");
        JBTReajustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTReajustarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JBTAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(JBTListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBTSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(JBTReajustar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(JBTLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(JBTSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jBTExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 321, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBTAlterar, JBTLimpar, JBTListar, JBTSair, jBTExcluir, jBTSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBTSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTListar)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTReajustar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBTSairActionPerformed

    private void JBTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTLimparActionPerformed
        jTFMarca.setText("");
        jTFModelo.setText("");
        jTFLugares.setText("");
        jTFValorAluguel.setText("");
        jTFPlaca.setText("");
    }//GEN-LAST:event_JBTLimparActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        if (!jTFPlaca.getText().equals("")) {
            Veiculo veiculo = new Veiculo();
            if (veiculoId != -1) {
                veiculo.setVeiculoId(veiculoId);
            }
            veiculo.setPlaca(jTFPlaca.getText());
            veiculo.setModelo(jTFModelo.getText());
            veiculo.setMarca(jTFMarca.getText());
            veiculo.setLugares(jTFLugares.getText());
            veiculo.setValorAluguel(jTFValorAluguel.getText());

            VeiculoDAO veiculodao = new VeiculoDAOMySQL();
            if (veiculodao.salvar(veiculo)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Veículo cadastrado com suscesso!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Veículo não cadastrado!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "O Nome deve ser preenchido!");
            jTFPlaca.requestFocus();
        }
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void JBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTListarActionPerformed
        //this.setVisible(false);
        new FrmVeiculoListar().setVisible(true);
    }//GEN-LAST:event_JBTListarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser excluído");
        VeiculoDAO veiculodao = new VeiculoDAOMySQL();
        Veiculo veiculo = veiculodao.consultarPK(id);
        if (veiculo != null) {
            jTFPlaca.setText(veiculo.getPlaca());
            jTFModelo.setText(veiculo.getModelo());
            jTFMarca.setText(veiculo.getMarca());
            jTFLugares.setText(veiculo.getLugares());
            jTFValorAluguel.setText(veiculo.getValorAluguel());
            Object[] opcoes = {"Sim", "Não"};
            int resposta = javax.swing.JOptionPane.showOptionDialog(null, "Confirma a exclusão do Veículo?", "Exclusão", 0, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
            if (resposta == 0) {
                if (veiculodao.apagarPK(Integer.parseInt(id))) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Veículo excluído com suscesso!");
                    jTFMarca.setText("");
                    jTFModelo.setText("");
                    jTFLugares.setText("");
                    jTFValorAluguel.setText("");
                    jTFPlaca.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Veículo não excluído!");
                }
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    private void JBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTAlterarActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser alterado");
        VeiculoDAO veiculodao = new VeiculoDAOMySQL();
        Veiculo veiculo = veiculodao.consultarPK(id);
        if (veiculo != null) {
            veiculoId = veiculo.getVeiculoId();
            jTFPlaca.setText(veiculo.getPlaca());
            jTFModelo.setText(veiculo.getModelo());
            jTFMarca.setText(veiculo.getMarca());
            jTFLugares.setText(veiculo.getLugares());
            jTFValorAluguel.setText(veiculo.getValorAluguel());
        }
    }//GEN-LAST:event_JBTAlterarActionPerformed

    private void JBTReajustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTReajustarActionPerformed
        double percentual = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("Digite o percentual de reajuste do \nvalor do aluguel dos veículos"));
        VeiculoDAO veiculodao = new VeiculoDAOMySQL();
        int resultado = veiculodao.reajustar(percentual);
        if (resultado != 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Foram reajustados o valor do aluguel de " + resultado + " Veículo(s)!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Nenhum Veículo foi reajustado!");
        }
    }//GEN-LAST:event_JBTReajustarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroVeiculo().setVisible(true);
            }
        });
    }
    private int veiculoId = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTAlterar;
    private javax.swing.JButton JBTLimpar;
    private javax.swing.JButton JBTListar;
    private javax.swing.JButton JBTReajustar;
    private javax.swing.JButton JBTSair;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTFLugares;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFPlaca;
    private javax.swing.JTextField jTFValorAluguel;
    // End of variables declaration//GEN-END:variables
}
